---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gientech.
--- DateTime: 2023/6/18 12:05
---
local cjson = require("cjson")

local json = cjson.new()

print("****************cjson encode***************")
local_array = { 1, 2, 3, 4, 5 }
print(json.encode(local_array))

-- 数值类型
local lua_number = 6.66
print(json.encode(lua_number))

-- 字符串类型
local lua_string = "I am lua-ejson"
print(json.encode(lua_string))

-- 对象类型
local lua_object = {
    ["name"] = "feng",
    ["age"] = 23,
    ["addr"] = "GuangZhou",
    ["email"] = "feng9662@qq.com",
    ["tel"] = "18866668888"
}
print(json.encode(lua_object))

local msg = {
    _cmd = "balllist",
    balls = {
        [1] = { id = 102, x = 10, y = 20, size = 1 },
        [2] = { id = 103, x = 10, y = 30, size = 2 },
    }
}
local buff = json.encode(msg)
print(buff)

print("******************cjson decode***************")
local raw = '{"balls":[{"x":10,"id":102,"size":1,"y":20},{"x":10,"id":103,"size":2,"y":30}],"_cmd":"balllist"}'
local data = json.decode(raw)
print(data)
print(data["_cmd"])
